exports.fileTypes = {
    '': 'Folder',
    '.zip': 'Compressed File',
    '.rar': 'Compressed RAR File',
    '.txt': 'Text Document',
    '.exe': 'Executable File',
    '.jpg': 'JPEG Image',
    '.mp4': 'Mp4 video',
    '.docx': 'Microsoft Office Word',
    '.doc': 'Microsoft Office Word',
    '.pdf': 'PDF Document',
    '.pptx': 'Microsoft Office Powerpoint',
    '.xlsx': 'Microsoft Office Excel',
    '.png': 'PNG Image',
    '.gif': 'GIF Image',
    '.svg': 'Scalable Vector Graphics',
    '.mp3': 'MP3 Audio',
    '.wav': 'WAV Audio',
    '.avi': 'AVI Video',
    '.mkv': 'MKV Video',
    '.mov': 'QuickTime Video',
    '.html': 'HTML Document',
    '.css': 'CSS Stylesheet',
    '.js': 'JavaScript File',
    '.py': 'Python Script',
    '.cpp': 'C++ Source Code',
    '.java': 'Java Source Code',
    '.csv': 'CSV File',
    '.json': 'JSON File',
    '.xml': 'XML Document',
    '.sql': 'SQL Script',
    '.zipx': 'Compressed ZIPX File',
    '.tar': 'Tar Archive',
    '.7z': '7-Zip Compressed File',
    '.iso': 'Disk Image',
    '.dmg': 'Mac OS X Disk Image',
    '.dll': 'Dynamic Link Library',
    '.jar': 'Java Archive',
    '.bak': 'Backup File',
    '.log': 'Log File',
    '.java': 'Java code',
}

exports.fileIcons = {
    '': '<i class="fa fa-folder"></i>',
    '.zip': '<i class="fa-solid fa-file-zipper"></i>',
    '.rar': '<i class="fa-solid fa-file-zipper"></i>',
    '.txt': '<i class="fa-solid fa-file-lines"></i>',
    '.exe': '<i class="fa-regular fa-file"></i>',
    '.jpg': '<i class="fa-solid fa-file-image"></i>',
    '.mp4': '<i class="fa-solid fa-file-video"></i>',
    '.docx': '<i class="fa-solid fa-file-word"></i>',
    '.doc': '<i class="fa-solid fa-file-word"></i>',
    '.pdf': '<i class="fa-solid fa-file-pdf"></i>',
    '.pptx': '<i class="fa-solid fa-file-powerpoint"></i>',
    '.xlsx': '<i class="fa-solid fa-file-excel"></i>',
    '.png': '<i class="fa-regular fa-image"></i>',
    '.gif': '<i class="fa-regular fa-image"></i>',
    '.svg': '<i class="fa-regular fa-image"></i>',
    '.mp3': '<i class="fa-solid fa-file-audio"></i>',
    '.wav': '<i class="fa-solid fa-file-audio"></i>',
    '.avi': '<i class="fa-solid fa-video"></i>',
    '.mkv': '<i class="fa-solid fa-video"></i>',
    '.mov': '<i class="fa-solid fa-video"></i>',
    '.html': '<i class="fa-brands fa-html5"></i>',
    '.css': '<i class="fa-brands fa-css3"></i>',
    '.js': '<i class="fa-brands fa-js"></i>',
    '.py': '<i class="fa-brands fa-python"></i>',
    '.cpp': '<i class="fa-solid fa-file-code"></i>',
    '.java': '<i class="fa-brands fa-java"></i>',
    '.csv': '<i class="fa-solid fa-file-csv"></i>',
    '.json': '<i class="fa-solid fa-file-code"></i>',
    '.xml': '<i class="fa-solid fa-file-code"></i>',
    '.sql': '<i class="fa-solid fa-file-code"></i>',
    '.zipx': '<i class="fa-solid fa-file-zipper"></i>',
    '.tar': '<i class="fa-solid fa-file-zipper"></i>',
    '.7z': '<i class="fa-solid fa-file-zipper"></i>',

}